# Gold layer: Product Sales Summary - Aggregated product performance metrics
pipeline: gold_analytics
flowgroup: product_sales_summary

actions:
  # Load products from bronze (batch mode for materialized view)
  - name: load_products
    type: load
    readMode: batch
    source:
      type: delta
      database: "{catalog}.{bronze_schema}"
      table: products
    target: v_products

  # Load orders fact from silver (batch mode for materialized view)
  - name: load_orders_for_products
    type: load
    readMode: batch
    source:
      type: delta
      database: "{catalog}.{silver_schema}"
      table: orders_fct
    target: v_orders_for_products

  # Aggregate product sales
  - name: product_sales_agg
    type: transform
    transform_type: sql
    source: v_orders_for_products
    target: v_product_sales_summary
    sql: |
      SELECT
        p.product_id,
        p.product_name,
        p.category,
        p.price as list_price,
        COUNT(o.order_id) as times_ordered,
        SUM(o.quantity) as total_quantity_sold,
        SUM(o.quantity * o.unit_price) as total_revenue,
        AVG(o.unit_price) as avg_selling_price
      FROM v_products p
      LEFT JOIN v_orders_for_products o ON p.product_id = o.product_id
      GROUP BY
        p.product_id, p.product_name, p.category, p.price

  # Write to gold layer as materialized view
  - name: write_product_sales_summary
    type: write
    source: v_product_sales_summary
    write_target:
      type: materialized_view
      database: "{catalog}.{gold_schema}"
      table: "product_sales_summary"
