# Product Performance Analytics - Gold Layer
# Creates product performance metrics for business intelligence

pipeline: gold_analytics
flowgroup: product_analytics

actions:
  # Load products from bronze layer
  - name: load_products_bronze
    type: load
    readMode: batch
    source:
      type: delta
      database: "{catalog}.{bronze_schema}"
      table: products
    target: v_products_bronze
    description: "Read products from bronze layer"

  # Load orders from silver layer
  - name: load_orders_silver
    type: load
    readMode: batch
    source:
      type: delta
      database: "{catalog}.{silver_schema}"
      table: orders_enriched
    target: v_orders_silver
    description: "Read enriched orders from silver layer"

  # Create product performance metrics
  - name: transform_product_performance
    type: transform
    transform_type: sql
    source: v_products_bronze
    target: v_product_performance
    sql: |
      WITH product_sales AS (
        SELECT
          product_id,
          COUNT(DISTINCT order_id) AS total_orders,
          SUM(quantity) AS total_units_sold,
          SUM(total_amount) AS total_revenue,
          COUNT(DISTINCT customer_id) AS unique_buyers,
          AVG(quantity) AS avg_units_per_order,
          MIN(order_date) AS first_sale_date,
          MAX(order_date) AS last_sale_date
        FROM v_orders_silver
        GROUP BY product_id
      ),
      product_rankings AS (
        SELECT
          product_id,
          total_revenue,
          RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank,
          RANK() OVER (ORDER BY total_units_sold DESC) AS units_rank,
          PERCENT_RANK() OVER (ORDER BY total_revenue DESC) AS revenue_percentile
        FROM product_sales
      )
      SELECT
        p.product_id,
        p.product_name,
        p.category,
        p.price AS list_price,
        p.stock_quantity AS current_stock,
        COALESCE(ps.total_orders, 0) AS total_orders,
        COALESCE(ps.total_units_sold, 0) AS total_units_sold,
        COALESCE(ps.total_revenue, 0) AS total_revenue,
        COALESCE(ps.unique_buyers, 0) AS unique_buyers,
        COALESCE(ps.avg_units_per_order, 0) AS avg_units_per_order,
        ps.first_sale_date,
        ps.last_sale_date,
        COALESCE(pr.revenue_rank, 0) AS revenue_rank,
        COALESCE(pr.units_rank, 0) AS units_rank,
        CASE
          WHEN pr.revenue_percentile <= 0.1 THEN 'Top 10%'
          WHEN pr.revenue_percentile <= 0.25 THEN 'Top 25%'
          WHEN pr.revenue_percentile <= 0.5 THEN 'Top 50%'
          ELSE 'Bottom 50%'
        END AS performance_tier,
        CASE
          WHEN p.stock_quantity = 0 THEN 'Out of Stock'
          WHEN p.stock_quantity < 10 THEN 'Low Stock'
          WHEN p.stock_quantity < 50 THEN 'Medium Stock'
          ELSE 'Well Stocked'
        END AS stock_status,
        CURRENT_TIMESTAMP() AS _gold_processing_timestamp
      FROM v_products_bronze p
      LEFT JOIN product_sales ps ON p.product_id = ps.product_id
      LEFT JOIN product_rankings pr ON p.product_id = pr.product_id

  # Write as materialized view
  - name: write_product_performance
    type: write
    source: v_product_performance
    write_target:
      type: materialized_view
      database: "{catalog}.{gold_schema}"
      table: product_performance
      properties:
        delta.autoOptimize.optimizeWrite: "true"
    description: "Product performance analytics view"
