# API Analytics Pipeline - Silver & Gold Layers
# Enriched analytics from JSONPlaceholder API data
# Generated by Lakehouse Plumber framework

import dlt
from pyspark.sql import functions as F
from pyspark.sql.window import Window

# ==============================================================================
# Pipeline Configuration
# ==============================================================================
PIPELINE_ID = "api_analytics"
CATALOG = spark.conf.get("catalog", "spalyam_catalog")
BRONZE_SCHEMA = spark.conf.get("bronze_schema", "bronze")
SILVER_SCHEMA = spark.conf.get("silver_schema", "silver")
GOLD_SCHEMA = spark.conf.get("gold_schema", "gold")

# ==============================================================================
# SILVER LAYER: Enriched Views
# ==============================================================================

# Read from Bronze tables
@dlt.view()
def v_bronze_users():
    """Read users from bronze layer"""
    return spark.read.table(f"{CATALOG}.{BRONZE_SCHEMA}.api_users")


@dlt.view()
def v_bronze_posts():
    """Read posts from bronze layer"""
    return spark.read.table(f"{CATALOG}.{BRONZE_SCHEMA}.api_posts")


@dlt.view()
def v_bronze_comments():
    """Read comments from bronze layer"""
    return spark.read.table(f"{CATALOG}.{BRONZE_SCHEMA}.api_comments")


@dlt.view()
def v_bronze_todos():
    """Read todos from bronze layer"""
    return spark.read.table(f"{CATALOG}.{BRONZE_SCHEMA}.api_todos")


# ==============================================================================
# SILVER: User Activity Summary
# ==============================================================================

@dlt.view()
def v_user_posts_summary():
    """Aggregate posts per user"""
    users_df = dlt.read("v_bronze_users")
    posts_df = dlt.read("v_bronze_posts")

    posts_agg = posts_df.groupBy("user_id").agg(
        F.count("post_id").alias("total_posts"),
        F.avg("word_count").alias("avg_post_word_count"),
        F.sum("content_length").alias("total_content_length")
    )

    return users_df.join(posts_agg, "user_id", "left").select(
        users_df.user_id,
        users_df.name,
        users_df.username,
        users_df.email,
        users_df.company_name,
        users_df.address_city,
        F.coalesce(posts_agg.total_posts, F.lit(0)).alias("total_posts"),
        F.coalesce(posts_agg.avg_post_word_count, F.lit(0)).alias("avg_post_word_count"),
        F.coalesce(posts_agg.total_content_length, F.lit(0)).alias("total_content_length")
    )


@dlt.table(
    name="user_activity_summary",
    comment="Silver layer: User activity summary with post metrics",
    table_properties={
        "delta.autoOptimize.optimizeWrite": "true",
        "quality": "silver"
    }
)
def user_activity_summary():
    """Silver table: User Activity Summary"""
    df = dlt.read("v_user_posts_summary")
    return df.withColumn("_silver_timestamp", F.current_timestamp())


# ==============================================================================
# SILVER: Post Engagement Metrics
# ==============================================================================

@dlt.view()
def v_post_engagement():
    """Calculate engagement metrics per post"""
    posts_df = dlt.read("v_bronze_posts")
    comments_df = dlt.read("v_bronze_comments")

    comments_agg = comments_df.groupBy("post_id").agg(
        F.count("comment_id").alias("comment_count"),
        F.countDistinct("email_domain").alias("unique_domains"),
        F.avg("comment_length").alias("avg_comment_length")
    )

    return posts_df.join(comments_agg, "post_id", "left").select(
        posts_df.post_id,
        posts_df.user_id,
        posts_df.title,
        posts_df.word_count,
        F.coalesce(comments_agg.comment_count, F.lit(0)).alias("comment_count"),
        F.coalesce(comments_agg.unique_domains, F.lit(0)).alias("unique_domains"),
        F.coalesce(comments_agg.avg_comment_length, F.lit(0)).alias("avg_comment_length")
    )


@dlt.table(
    name="post_engagement",
    comment="Silver layer: Post engagement metrics with comment analysis",
    table_properties={
        "delta.autoOptimize.optimizeWrite": "true",
        "quality": "silver"
    }
)
def post_engagement():
    """Silver table: Post Engagement"""
    df = dlt.read("v_post_engagement")
    return df.withColumn("_silver_timestamp", F.current_timestamp())


# ==============================================================================
# SILVER: User Productivity (Todos Analysis)
# ==============================================================================

@dlt.view()
def v_user_productivity():
    """Calculate user productivity from todos"""
    users_df = dlt.read("v_bronze_users")
    todos_df = dlt.read("v_bronze_todos")

    todos_agg = todos_df.groupBy("user_id").agg(
        F.count("todo_id").alias("total_todos"),
        F.sum(F.when(F.col("is_completed"), 1).otherwise(0)).alias("completed_todos")
    ).withColumn(
        "completion_rate",
        F.round(F.col("completed_todos") * 100.0 / F.col("total_todos"), 2)
    )

    return users_df.join(todos_agg, "user_id", "left").select(
        users_df.user_id,
        users_df.name,
        users_df.company_name,
        F.coalesce(todos_agg.total_todos, F.lit(0)).alias("total_todos"),
        F.coalesce(todos_agg.completed_todos, F.lit(0)).alias("completed_todos"),
        F.coalesce(todos_agg.completion_rate, F.lit(0)).alias("completion_rate")
    )


@dlt.table(
    name="user_productivity",
    comment="Silver layer: User productivity metrics from todos",
    table_properties={
        "delta.autoOptimize.optimizeWrite": "true",
        "quality": "silver"
    }
)
def user_productivity():
    """Silver table: User Productivity"""
    df = dlt.read("v_user_productivity")
    return df.withColumn("_silver_timestamp", F.current_timestamp())


# ==============================================================================
# GOLD LAYER: Business Analytics
# ==============================================================================

@dlt.view()
def v_user_360():
    """Comprehensive user view combining all metrics"""
    activity = dlt.read("user_activity_summary")
    productivity = dlt.read("user_productivity")

    return activity.join(
        productivity.select("user_id", "total_todos", "completed_todos", "completion_rate"),
        "user_id",
        "left"
    ).withColumn(
        "engagement_score",
        F.round(
            (F.col("total_posts") * 10) +
            (F.col("completion_rate") * 0.5) +
            (F.col("avg_post_word_count") * 0.1),
            2
        )
    ).withColumn(
        "user_segment",
        F.when(F.col("engagement_score") >= 100, "Power User")
         .when(F.col("engagement_score") >= 50, "Active User")
         .when(F.col("engagement_score") >= 20, "Regular User")
         .otherwise("Casual User")
    )


@dlt.table(
    name="api_user_360",
    comment="Gold layer: Comprehensive user 360 view with engagement scoring",
    table_properties={
        "delta.autoOptimize.optimizeWrite": "true",
        "quality": "gold"
    }
)
def api_user_360():
    """Gold table: User 360 View"""
    df = dlt.read("v_user_360")
    return df.withColumn("_gold_timestamp", F.current_timestamp())


@dlt.view()
def v_content_analytics():
    """Content analytics aggregated by company"""
    users = dlt.read("v_bronze_users")
    posts = dlt.read("v_bronze_posts")
    engagement = dlt.read("post_engagement")

    user_posts = posts.join(users.select("user_id", "company_name"), "user_id", "left")

    return user_posts.join(
        engagement.select("post_id", "comment_count", "unique_domains"),
        "post_id",
        "left"
    ).groupBy("company_name").agg(
        F.count("post_id").alias("total_posts"),
        F.sum("comment_count").alias("total_comments"),
        F.avg("word_count").alias("avg_post_length"),
        F.avg("comment_count").alias("avg_comments_per_post"),
        F.sum("unique_domains").alias("total_unique_commenters")
    )


@dlt.table(
    name="api_content_analytics",
    comment="Gold layer: Content analytics by company",
    table_properties={
        "delta.autoOptimize.optimizeWrite": "true",
        "quality": "gold"
    }
)
def api_content_analytics():
    """Gold table: Content Analytics by Company"""
    df = dlt.read("v_content_analytics")
    return df.withColumn("_gold_timestamp", F.current_timestamp())


@dlt.view()
def v_platform_summary():
    """Overall platform summary metrics"""
    users = dlt.read("v_bronze_users")
    posts = dlt.read("v_bronze_posts")
    comments = dlt.read("v_bronze_comments")
    todos = dlt.read("v_bronze_todos")

    return spark.createDataFrame([{
        "total_users": users.count(),
        "total_posts": posts.count(),
        "total_comments": comments.count(),
        "total_todos": todos.count(),
        "avg_posts_per_user": posts.count() / max(users.count(), 1),
        "avg_comments_per_post": comments.count() / max(posts.count(), 1),
        "completed_todos_pct": todos.filter(F.col("is_completed")).count() * 100.0 / max(todos.count(), 1)
    }])


@dlt.table(
    name="api_platform_summary",
    comment="Gold layer: Overall platform summary metrics",
    table_properties={
        "delta.autoOptimize.optimizeWrite": "true",
        "quality": "gold"
    }
)
def api_platform_summary():
    """Gold table: Platform Summary"""
    df = dlt.read("v_platform_summary")
    return df.withColumn("_gold_timestamp", F.current_timestamp()) \
             .withColumn("report_date", F.current_date())
